CREATE TABLE IF NOT EXISTS DEPARTMENT (
    EMPLOYEE_ID TEXT,
    NAME TEXT,
    DEPARTMENT_ID TEXT,
    MANAGER_ID TEXT,
    SALARY REAL
);

INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
('100', 'STEVEN', '90', '100', 24000),
('101', 'CLARK', '90', '100', 22000),
('102', 'MILLER', '60', '102', 17000),
('103', 'SMITH', '90', '103', 15000),
('104', 'ADAMS', '50', '103', 12000),
('105', 'LUV', '60', '102', 42000),
('106', 'DAVID', '50', '100', 5000);



SELECT DEPARTMENT_ID AS "Department Code",
    COUNT(*) AS "NO OF EMPLOYEES",
    SUM(salary) AS "Total Salary"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SUM(salary)
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS "Department Code",
    COUNT(*) AS "No of Employees",
    SUM(salary) AS "Total Salary"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS "Department Code",
      SUM(salary) AS "Total Salary"
FROM DEPARTMENT
WHERE MANAGER_ID = '103'
GROUP BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID, COUNT(*) AS "No of Employees"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 2;

