CREATE TABLE IF NOT EXISTS PRODUCT (
    PRO_ID TEXT PRIMARY KEY,
    PRO_NAME TEXT,
    PRO_PRICE TEXT,
    PRO_COM TEXT
);

INSERT INTO PRODUCT(PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM)
VALUES
('P001','LAPTOP','50000','Dell'),
('P002','Smartphoone','20000','Samsung'),
('P003','Tablet','15000','Apple'),
('P004','Headphones','3000','Sony'),
('P005','Smartwatch','10000','Fitbit');

SELECT PRO_NAME,PRO_PRICE
      FROM PRODUCT
      WHERE PRO_PRICE =
      (SELECT MIN(PRO_PRICE) FROM PRODUCT);
SELECT PRO_NAME,PRO_PRICE
      FROM PRODUCT
      WHERE PRO_PRICE =
      (SELECT MAX(PRO_PRICE) FROM PRODUCT);